name: Docker Image CI

on:
  push:
    branch: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image:  sonar-cnes-report
          tags: latest, ${{env.SONAR_CNES_REPORT_VERSION_ARG}}
          buildArgs: SONAR_CNES_REPORT_VERSION=${{env.SONAR_CNES_REPORT_VERSION_ARG}}
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
